Dockerfile, README.md, osint/individuals.json, osint/reputation.json, phoneinfoga.py
👋 Hi there! I saw in your wiki that you're thinking of using a Docker image for your cool project.
Do you mind taking a look at these changes, and see if they'd be useful for you?
I'll try to explain what I'm proposing:
1. I've used `jfloff/alpine-python:3.6-onbuild` as the base Docker image, it's a smaller image than using Ubuntu, or Python3, and it comes with an automatic step of installing the `requirements.txt`if found.
2. After everything's installed, I use your script as the entry point, so when executing commands in the container, you won't have to know the inner directory layout to find the script, it'll just accept arguments.
3. I've added some notes in the README as well on how to get this running.
Cheers!
=> Introduced basic Docker support

README.md, osint/reputation.json
- Added a logo to the Readme
- Added uk.popularphotolook.com reputation source
- Fix Google search broken urls filter  (https://github.com/sundowndev/PhoneInfoga/commit/9df382bd48f65ef799c91b50be7f6731cee5e9b0)
- Fix wrong Google Dork operators resulting in bad footprinting behavior (https://github.com/sundowndev/PhoneInfoga/commit/e28e4c5413824f9d956794c7062edd3d640786ba)
=> v1.6.7 release

lib/googlesearch.py
=> Add exception in google search using api key

lib/banner.py, lib/googlesearch.py, lib/output.py, scanners/footprints.py
Fix for #65 - The tool verify if output option is enabled so he disable the logger to ask for command-line user input.
=> [Fix] Handle output and footprinting together

.gitignore, README.md, docker-compose.yml, docs/contribute.md, docs/formatting.md, docs/googlesearch.md, docs/index.md, docs/install.md, docs/resources.md, docs/usage.md, lib/banner.py, lib/googlesearch.py, mkdocs.yml, phoneinfoga.py, requirements.txt, scanners/footprints.py, scanners/recon.py
=> [Fix] implement Selenium to handle Google captcha

docs/googlesearch.md
=> refactor(docs): fix links

requirements.txt
=> Add config package to the requirements

docs/install.md
=> Docs: remove references to wget

docs/install.md
=> Fix a typo in docs about installing geckodriver

api/controllers.go, api/server_test.go, api/validators.go, cmd/recon.go, cmd/scan.go, cmd/serve.go, cmd/version.go, docs/go-module-usage.md, go.mod, go.sum, main.go, pkg/scanners/google_test.go, pkg/scanners/local.go, pkg/scanners/local_test.go, pkg/scanners/ovh_test.go, pkg/scanners/scanners.go
To be used as `go get gopkg.in/sundowndev/phoneinfoga.v2`
=> Use a v2 go module path

.github/workflows/build.yml, api/server.go, api/server_test.go, go.sum
- Override index.html path
- Add a benchmark for API server
- Test health handler
- Test client static route
=> Improve api unit tests

client/src/App.vue, client/src/components/GoogleSearch.vue, client/src/components/LocalScan.vue, client/src/components/NumverifyScan.vue, client/src/components/OVHScan.vue, client/src/views/Scan.vue
- UI: Improve scanners error handling with alerts
- UI: Add software version in footer
=> Improve scanners error handling

docs/install.md
bump version in terminal installation command
=> docs: bump version in terminal installation command

scripts/install, scripts/install.sh
=> Create installation bash script for UNIX systems

.github/workflows/build.yml, .github/workflows/client.yml, .github/workflows/goreleaser.yml
So workflows can run on pull requests from forks as well
=> Fix CI workflows target events

.github/workflows/dockerimage.yml
related to #725
- linux/amd64
- linux/arm/v7
- linux/arm64
- https://github.com/docker/build-push-action
- https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
=> Add multi-arch support for docker image

Dockerfile, api/docs/docs.go, api/docs/swagger.json, api/docs/swagger.yaml, api/server.go, cmd/version.go, docs/index.md, docs/install.md, mkdocs.yml
=> changed all broken URL of repo

.github/dependabot.yml
=> Remove npm and Gomod from dependabot config

docs/scanners.md
This PR specify default values for Numverify configuration parameters.
=> Improve docs for Numverify configuration

cmd/serve.go
=> cmd/serve: print port number

support/scripts/install
Closes https://github.com/sundowndev/phoneinfoga/issues/1080
=> Fix installation script

lib/remote/init.go, lib/remote/remote.go, lib/remote/remote_test.go, lib/remote/suppliers/numverify.go
This PR adds capability to run scanners in parallel.
=> Run scanners parallelly

.github/workflows/build.yml, .gitignore, Makefile, api/controllers.go, api/docs/docs.go, api/docs/swagger.json, api/docs/swagger.yaml, api/server.go, go.mod, lib/remote/suppliers/numverify.go
This PR adds a Makefile to run scripts. Also formatted Go files and removed Deprecated tag for OVH scan in the REST API's specs.
=> Add Makefile

.github/workflows/build.yml, Makefile, api/server.go, go.mod, go.sum
This PR enhances the local dev environment with few changes. The install-tools script now install every dependencies needed to build. Ran go mod tidy. Build script now put the binary in the bin folder.
=> Improve install tools script

.dockerignore, Dockerfile, Makefile, build/build.go, build/build_test.go, cmd/version.go, support/scripts/format
- Fix Dockerfile that missed dev tools to build the project
- Delete unused format script
- Add some functions to the build package
=> Fix Dockerfile

cmd/scan.go, lib/filter/filter.go, lib/filter/filter_test.go, lib/remote/googlesearch_scanner_test.go, lib/remote/local_scanner_test.go, lib/remote/numverify_scanner_test.go, lib/remote/ovh_scanner_test.go, lib/remote/remote.go, lib/remote/remote_test.go
=> Add disable CLI flag

lib/remote/suppliers/ovh.go, lib/remote/suppliers/ovh_test.go
=> Fix error handling in ovh supplier

docs/getting-started/install.md
This PR updates install instructions.
=> Install instructions

docs/getting-started/usage.md
The format of the change can be reviewed via the rendered version of the file here https://github.com/sundowndev/phoneinfoga/blob/bb7d80a1a124344939a28ff550c598826a7f058e/docs/getting-started/usage.md
=> add docker commands to usage.md; to aid getting started

docs/getting-started/install.md
Following #1194, we have to update install instruction to fix the install script usage.
=> Improve install instructions

cmd/root.go, cmd/scan.go, web/v2/api/server/server.go
Tested on the terminal powershell and cmd.
Resolves #1243
=> fix: colored text on windows

build/build.go, build/build_test.go, web/client/src/App.vue, web/client/yarn.lock, web/controllers.go, web/docs/docs.go, web/docs/swagger.json, web/docs/swagger.yaml, web/server_test.go
This PR implements analytics in the web client (demo only). API requests are not monitored.
=> Implement analytics in demo website

.github/workflows/build.yml, .github/workflows/client.yml, .github/workflows/release.yml, Dockerfile, web/client/package.json, web/client/src/App.vue, web/client/src/components/Scanner.vue, web/client/yarn.lock
This PR upgrades node and fixes build issues with node v20.3.1
fixes #1297
=> Upgrade nodejs to 20.3.1

docs/getting-started/scanners.md
Hey so I had an issue as I first signed up to Numverify (didn't follow the link) and when I was looking up on the issue, I saw a few other people also went to Numverify directly, so I added a little P.S. to the web doc. Figured it would help out a few people
If you like it, please approve.
=> Added a little ps about Numverify
